language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql

cache:
  directories:
    - "node_modules"

env:
  - NODE_ENV=test
before_script:
- psql -c 'create database postgrestest;' -U postgres
- psql -c "CREATE USER mavis WITH PASSWORD 'mavis';" -U postgres
- npm i nyc -g

script: npm run test

after_success:
  - npm run coverage
